# Generated by Django 4.0.6 on 2022-07-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restuarant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Location', models.TextField()),
                ('Cuisines', models.TextField()),
                ('Veg', models.BooleanField()),
                ('Rating', models.FloatField()),
                ('Contact', models.CharField(max_length=10)),
                ('Emai', models.EmailField(max_length=254)),
            ],
        ),
    ]
