# Generated by Django 4.0.6 on 2022-07-04 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuisines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisines_type', models.CharField(max_length=120)),
                ('restuarant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restuarant.restuarant')),
            ],
        ),
    ]
