# Generated by Django 4.0.6 on 2022-07-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant', '0002_cuisines'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cuisines_type', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('veg', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='cuisines',
            old_name='restuarant',
            new_name='restuarant_id',
        ),
        migrations.RenameField(
            model_name='restuarant',
            old_name='Name',
            new_name='restuarant_Name',
        ),
    ]
