# Generated by Django 4.0.6 on 2022-07-04 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant', '0003_menu_rename_restuarant_cuisines_restuarant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='cuisines_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restuarant.cuisines'),
        ),
    ]
