# Generated by Django 4.0.6 on 2022-07-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant', '0004_alter_menu_cuisines_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='restuarant',
            name='discriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
