# Generated by Django 4.0.6 on 2022-07-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant', '0007_remove_cuisines_restuarant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restuarant',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='restuarant',
            old_name='Cuisines',
            new_name='cuisines',
        ),
        migrations.RenameField(
            model_name='restuarant',
            old_name='Emai',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='restuarant',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='restuarant',
            old_name='restuarant_Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='restuarant',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='restuarant',
            name='Veg',
        ),
        migrations.AddField(
            model_name='restuarant',
            name='type',
            field=models.TextField(choices=[('1', 'veg'), ('2', 'non-veg')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
