# Generated by Django 4.0.6 on 2022-07-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant', '0008_rename_contact_restuarant_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='veg',
        ),
        migrations.AddField(
            model_name='menu',
            name='type',
            field=models.TextField(choices=[('1', 'veg'), ('2', 'non-veg')], default='1', max_length=10),
        ),
    ]
