# Generated by Django 4.0.6 on 2022-07-05 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant', '0009_remove_menu_veg_menu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='cuisines_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisine', to='restuarant.cuisines'),
        ),
    ]
