# Generated by Django 4.0.6 on 2022-07-05 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant', '0010_alter_menu_cuisines_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='rname',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='rname', to='restuarant.restuarant'),
        ),
    ]
