# Generated by Django 4.0.6 on 2022-07-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant', '0011_menu_rname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restuarant',
            name='type',
            field=models.TextField(choices=[('veg', 'veg'), ('non-veg', 'non-veg')], default='1', max_length=10),
        ),
    ]
