# Generated by Django 4.0.6 on 2022-07-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant', '0014_alter_menu_rname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='type',
            new_name='veg_type',
        ),
        migrations.RenameField(
            model_name='restuarant',
            old_name='type',
            new_name='veg_type',
        ),
    ]
